// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzvK0diPw7AIvzQKUBVmq14XXMU3fpiWk',
    appId: '1:639858200492:web:2459e543dd5fe05afbf409',
    messagingSenderId: '639858200492',
    projectId: 'iot-devicesensor',
    authDomain: 'iot-devicesensor.firebaseapp.com',
    storageBucket: 'iot-devicesensor.appspot.com',
    measurementId: 'G-04W7FSN8DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFVTPVAEwrYrB2Y0eSlsHWn8kBIbVKbds',
    appId: '1:639858200492:android:6ca6526a33dae3cbfbf409',
    messagingSenderId: '639858200492',
    projectId: 'iot-devicesensor',
    storageBucket: 'iot-devicesensor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFti_i6ibtvBS3BmXGqEmoRQ2YyV7bOrc',
    appId: '1:639858200492:ios:2bd38aa9195369cefbf409',
    messagingSenderId: '639858200492',
    projectId: 'iot-devicesensor',
    storageBucket: 'iot-devicesensor.appspot.com',
    iosBundleId: 'com.example.mobileSensors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFti_i6ibtvBS3BmXGqEmoRQ2YyV7bOrc',
    appId: '1:639858200492:ios:dc416302d1cd39c2fbf409',
    messagingSenderId: '639858200492',
    projectId: 'iot-devicesensor',
    storageBucket: 'iot-devicesensor.appspot.com',
    iosBundleId: 'com.example.mobileSensors.RunnerTests',
  );
}
